resolver: lts-5.0
packages:
- '.'
extra-deps:
  - Cabal-1.22.5.0
  - cabal-macosx-0.2.3.4
  - reactive-banana-1.1.0.1
  - reactive-banana-wx-1.1.1.0
  - wx-0.92.2.0
  - wxcore-0.92.2.0
  - wxc-0.92.2.0
  - wxdirect-0.92.2.0

explicit-setup-deps:
  "reactive-banana-wx": true
